name = "status"
workers_dev = true
account_id = "cfdc1345e7a00ad943b2eb72302f521a"
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2021-07-23"

[triggers]
crons = ["*/3 * * * *"]

[site]
bucket = "out"
entry-point = "./"

# uncomment and adjust following if you are not using GitHub Actions
[env.production]
kv_namespaces = [ 
	 { binding = "KV_STATUS_PAGE", id = "3e5fb2147bde4398a74a2ca575569728" }
]
#zone_id="xxx"
#route="xxx"
